### ISSUE TITLE
Update height if contents change

### ISSUE THREAD

**Issue by schellenbergk** [Alhadis/Accordion#10]
Hello, great plugin,

Is there a way to update height of accordion item if content is updated within it? Thanks.

**Comment by Alhadis** [comment]
I realise how lacking this repository is when it comes to real-life examples. :disappointed: My apologies.

Yes, but the resizing needs to be done manually. You achieve this by calling the fold's [`.fit()` method](https://github.com/Alhadis/Accordion/blob/master/docs/fold.adoc#fit) when an image loads:

~~~js
// Add the end of your document (or similar)
for(const img of document.images){
	img.addEventListener("load", event => {
		const imgElement = event.target;
		
		// Locate the `Fold` instance which contains this <img> node
		const fold = Accordion.getFold(imgElement);

		fold.fit();
	});
}
~~~

Due to the natural delay between loading a network resource and determining the width and height of an image's boundaries, it might be necessary to call `fit();` after a short timeout, to give the browser a chance to handle the `load` event, as well as to finish reading in the dimensions of the loaded resource:

~~~js
fold.fit();
setTimeout(() => fold.fit(), 10); // Tweak delay as desired
~~~

This is done manually because the `Accordion` class only updates its metrics when the user's toggling folds or resizing the browser viewport. There's no efficient way to monitor sudden changes to content when images load, and doing so would be a waste of cycles for minimal gain.

**Comment by schellenbergk** [comment]
I've tried your suggestion but the .fit() method on fold does not seem to work (I'm only able to get the fold to correct size if I close and reopen the fold.

By the way I'm not loading images but I'm inserting new elements inside the fold..  Here's the code I've been playing with:

```
let row = e.target.closest('.row');
let table = e.target.closest('.table');
let clone = row.cloneNode(true);

row.parentNode.insertBefore(clone,row);

//update Accordion fold height
let fold = Accordion.getFold(clone);
fold.fit();
setTimeout(()=>{
  fold.fit();
},100);

//Also tried later on in console with no success:
Accordion.getFold(document.body.getElementsByClassName('.table')[0]).fit();
```
Thanks.

**Comment by Alhadis** [comment]
Ah, sorry, I should have asked about if you were dynamically inserting images (that's the reason the Accordion doesn't listen for `load` events upon initialisation, BTW: it'd be inconsistent).

Your best bet is to use the Accordion instance's [`.update()`](https://github.com/Alhadis/Accordion/blob/master/docs/accordion.adoc#update) method instead. You can gain a handle on the instance from the DOM using `Accordion.getAccordion` (just like with folds).

**Comment by Alhadis** [comment]
BTW, my recommended approach would be to update the fold as you're dynamically inserting images. If all else fails, you can simply use `setInterval` to call `update` repeatedly, even when it isn't needed. That's going to be slow if the Accordion is huge with hundreds of folds, but for most applications, it shouldn't be a problem. =)

**Comment by schellenbergk** [comment]
Boomshakalaka!!! Worked like a charm, Thanks so much for your help!!!

**Comment by Alhadis** [comment]
My pleasure! :grin: Please let me know if you have any other questions or troubles.

(I should really extend that `README`...)
