### ISSUE TITLE
Great Plugin

### ISSUE THREAD

**Issue by schellenbergk** [Alhadis/Accordion#9]
Is there an easy way to keep first item expanded by default.  Also when expanding a new element collapse the previous one? Thanks.

**Comment by Alhadis** [comment]
:wave: Hey mate,

1. Yes, just add the `open` class to the first fold *before* creating the `Accordion` instance.

2. To collapse other elements when expanding a new one, add this to your `Accordion`'s  instance:

~~~js
onToggle: function(target){
	target.accordion.folds.forEach(fold => {
		if(fold !== target)
			old.open = false;
	});
}
~~~

**Comment by schellenbergk** [comment]
Thanks!!!

**Comment by schellenbergk** [comment]
thanks!!, just correct that mistake `old.open = false;` ;)

**Comment by Alhadis** [comment]
@schellenbergk I'm glad I could help. Since you're not the first person to ask about this, I think I *will* make this a core option after all. Looking back, my decision to optimise space by omitting a `modal` option really doesn't justify the added effort required of authors.

Expect a new release in the near future that will allow you to implement the above behaviour simply by passing `modal: true` as an option. =)
